#!/usr/bin/env python3
"""Merge PT MT-drafts into gsm8k_extracted.json. These are careful
draft translations (numbers and names preserved exactly, natural
pt-PT phrasing) but are DRAFTS — the protocol (PRISM_SPEC.md §3,
updated after the pilot's comprehension-cliff finding) requires a
native post-edit pass before these count as localized. Until that
happens, content.pt stays null in the task file used for real runs;
this script writes a SEPARATE _draft_pt.json for review, and only
merges into the real suite file when told to.
"""
import json
from pathlib import Path

TRANSLATIONS = {
"gsm_001": "O Josh decide experimentar comprar casas para renovar e revender. Compra uma casa por $80.000 e depois investe $50.000 em obras. Isto aumentou o valor da casa em 150%. Qual foi o lucro que ele obteve? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_002": "A Carla está a descarregar um ficheiro de 200 GB. Normalmente consegue descarregar a 2 GB/minuto, mas quando o download vai a 40% do caminho, o Windows força um reinício para instalar atualizações, o que demora 20 minutos. Depois a Carla tem de recomeçar o download do zero. Quanto tempo demora a descarregar o ficheiro? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_003": "O John conduz durante 3 horas a uma velocidade de 60 mph e depois dá a volta porque percebe que se esqueceu de algo muito importante em casa. Tenta chegar a casa em 4 horas, mas passa as primeiras 2 horas parado no trânsito. Passa a meia hora seguinte a conduzir a 30 mph, antes de conseguir percorrer o tempo restante das 4 horas a 80 mph. A que distância de casa está ele no final dessas 4 horas? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_004": "A taxa horária da Eliza para as primeiras 40 horas que trabalha por semana é de $10. Ela recebe também um pagamento de horas extra de 1,2 vezes a sua taxa horária normal. Se a Eliza trabalhou 45 horas esta semana, quanto são os seus ganhos esta semana? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_005": "A Toula foi à pastelaria e comprou vários tipos de pastelaria. Comprou 3 dúzias de donuts que custam $68 por dúzia, 2 dúzias de mini cupcakes que custam $80 por dúzia, e 6 dúzias de mini cheesecakes por $55 a dúzia. Qual foi o custo total? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_006": "O Carlos está a plantar uma limoeiro. A árvore vai custar $90 para plantar. Todos os anos vai dar 7 limões, que ele pode vender a $1,5 cada. Custa $3 por ano para regar e adubar a árvore. Quantos anos vai demorar até ele começar a ganhar dinheiro com a árvore? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_007": "Dois comboios partem de San Rafael ao mesmo tempo. Começam por viajar para oeste, ambos percorrendo 80 milhas. No dia seguinte, viajam para norte, percorrendo 150 milhas. Qual é a distância percorrida por cada comboio nos dois dias? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_008": "A Jill recebe $20 por hora para dar aulas e $30 para ser treinadora de cheerleading. Se ela trabalha 50 semanas por ano, 35 horas por semana como professora e 15 horas por semana como treinadora, qual é o seu salário anual? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_009": "A Claire faz uma omelete de 3 ovos todas as manhãs ao pequeno-almoço. Quantas dúzias de ovos vai comer em 4 semanas? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_010": "A Marissa está a fazer um trilho de 12 milhas. Demorou 1 hora a andar as primeiras 4 milhas, depois mais uma hora a andar as duas milhas seguintes. Se ela quer que a sua velocidade média seja de 4 milhas por hora, a que velocidade (em milhas por hora) precisa de andar a distância restante? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_011": "O Billy vende DVDs. Tem 8 clientes na terça-feira. Os primeiros 3 clientes compram um DVD cada. Os 2 clientes seguintes compram 2 DVDs cada. Os últimos 3 clientes não compram nenhum DVD. Quantos DVDs vendeu o Billy na terça-feira? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_012": "A Marie pediu uma refeição de frango que custa $12, 5 pacotes de leite que custam $3 cada, 4 maçãs que custam $1,50 cada, e algumas caixas de piza. A Marie pagou um total de $50. Quantas caixas de piza é que a Marie pediu se cada caixa custa $8,50? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_013": "As idades do Darrell e do Allen estão na razão de 7:11. Se a soma das suas idades agora é 162, calcula a idade do Allen daqui a 10 anos. Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_014": "O Gunter está a tentar contar os rebuçados de gelatina num frasco. Pergunta aos amigos quantos acham que há no frasco. Um diz 80. Outro diz 20 a mais do que metade do primeiro. Um terceiro diz 25% a mais do que o primeiro. Qual é a média dos palpites deles? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_015": "O Mike joga ténis de mesa durante 40 minutos. Nos primeiros 20 minutos, marca 4 pontos. Nos segundos 20 minutos, marca 25% mais pontos. Quantos pontos marcou no total? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_016": "O Terry come 2 iogurtes por dia. Estão atualmente em promoção a 4 iogurtes por $5,00. Quanto gasta em iogurtes ao longo de 30 dias? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_017": "O John compra o dobro de gravatas vermelhas do que gravatas azuis. As gravatas vermelhas custam 50% mais do que as azuis. Ele gastou $200 em gravatas azuis que custam $40 cada. Quanto gastou em gravatas no total? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_018": "O Lloyd tem uma quinta de ovos. As suas galinhas produzem 252 ovos por dia e ele vende-os a $2 a dúzia. Quanto ganha o Lloyd com ovos por semana? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_019": "O barco do Tom consegue viajar a 10 milhas por hora. Ele navega das 13h às 16h. Depois viaja de volta a uma velocidade de 6 mph. Quanto tempo demora a voltar? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_020": "Um mecânico cobra tarifas diferentes para reparar pneus de camiões e de carros. Por cada pneu de camião reparado, o mecânico cobra $60 e por cada pneu de carro reparado, cobra $40. Na quinta-feira, o mecânico repara 6 pneus de camião e 4 pneus de carro. Na sexta-feira, repara 12 pneus de carro e não repara nenhum pneu de camião. Quanto mais receita ganhou o mecânico no dia com maior receita? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_021": "As irmãs Doubtfire estão a conduzir para casa com 7 gatinhos adotados do abrigo de animais local quando a mãe delas liga a informar que as suas duas gatas de casa acabaram de ter gatinhos. Ela diz que a Patchy, a primeira gata, teve o triplo do número de gatinhos adotados, enquanto a Trixie, a outra gata, teve 12. Quantos gatinhos tem agora a família Doubtfire? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_022": "Um cesto contém 25 laranjas das quais 1 está estragada, 20% estão verdes, 2 estão azedas e o resto está bom. Quantas laranjas estão boas? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_023": "Há o dobro de rapazes do que raparigas na escola do Dr. Wertz. Se há 60 raparigas e 5 alunos por cada professor, quantos professores há? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_024": "A Judy dá 5 aulas de dança todos os dias, de segunda a sexta, e 8 aulas no sábado. Se cada aula tem 15 alunos e ela cobra $15,00 por aluno, quanto dinheiro ganha numa semana? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_025": "O Tommy está a angariar fundos para a sua instituição de caridade vendendo brownies a $3 a fatia e cheesecakes a $4 a fatia. Se o Tommy vende 43 brownies e 23 fatias de cheesecake, quanto dinheiro angaria? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_026": "O Artie tem uma banca de flores no Mercado dos Agricultores. Vende três tipos de flores: malmequeres, petúnias e begónias. Normalmente vende os malmequeres a $2,74 por vaso, as petúnias a $1,87 por vaso e as begónias a $2,12 por vaso. O Artie não tem troco hoje, por isso decidiu arredondar todos os preços ao dólar mais próximo. Se o Artie vender 12 vasos de malmequeres, 9 vasos de petúnias e 17 vasos de begónias, quanto vai ganhar? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_027": "O Vincent pode comprar flores em pacotes de 3 por $2,50 ou em pacotes de 2 por $1. Quanto dinheiro poupa comprando 18 flores ao preço mais vantajoso? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_028": "Duas raparigas receberam cada uma 1/6 dos 24 litros de água. Depois um rapaz recebeu 6 litros de água. Quantos litros de água sobraram? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_029": "O Gene está a coser uma colcha com t-shirts antigas de recordação. Tem uma t-shirt de cada férias em que esteve. Cada t-shirt é o seu próprio quadrado da colcha. Cada fila é feita de quadrados de um ano diferente de férias. Ele vai de férias quatro vezes por ano e tem tirado férias desde os 23 anos. Ele tem agora 34 anos. Quantos quadrados tem a colcha no total? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_030": "Uma empresa paga a cada um dos seus funcionários $600 por mês. A empresa tem a política de aumentar os salários de cada funcionário em 10% do salário inicial todos os anos, para quem estiver na empresa há cinco anos. Se a Sylvie acabou de completar 5 anos na empresa em dezembro passado, qual é o seu salário anual depois de mais três anos de serviço? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_031": "Num bairro, o número de coelhos como animais de estimação é doze a menos do que o número combinado de cães e gatos de estimação. Se há dois gatos por cada cão, e o número de cães é 60, quantos animais de estimação há no total no bairro? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_032": "Quando a Freda cozinha tomate enlatado para fazer molho, este perde metade do volume. Cada lata de 16 onças de tomate que ela usa contém três tomates. O último lote de molho de tomate da Freda fez 32 onças de molho. Quantos tomates usou a Freda? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_033": "A Mary é uma jardineira entusiasta. Ontem, recebeu 18 novas plantas em vaso do seu viveiro de plantas preferido. Ela já tem 2 plantas em vaso em cada um dos 40 parapeitos de janela da sua grande casa de campo. Sentindo-se generosa, decidiu que vai dar 1 planta em vaso de cada parapeito a amigos e família amanhã. Com quantas plantas em vaso vai a Mary ficar? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_034": "O Jerome teve 4 amigos que o vieram visitar num certo dia. O primeiro amigo tocou à campainha 20 vezes antes de o Jerome abrir, o segundo amigo tocou à campainha 1/4 vezes mais do que o primeiro amigo do Jerome. O terceiro amigo tocou à campainha 10 vezes mais do que o quarto amigo. Se o quarto amigo tocou à campainha 60 vezes, quantas vezes tocou a campainha no total? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_035": "O Solo tem de ler 4 páginas do seu manual de Ciências, 20 páginas do seu manual de Estudos Sociais, 7 páginas do seu manual de História e 8 páginas do seu manual de Geografia. O Solo leu 15 páginas na segunda-feira. Se tem mais 4 dias para completar toda a leitura, quantas páginas precisa de ler, em média, por dia? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_036": "O John gosta de beber um copo de água ao pequeno-almoço, almoço e jantar. Por fim, bebe mais um antes de ir dormir. O John faz isto todos os dias de semana, mas ao fim de semana gosta de relaxar e bebe um refrigerante ao jantar em vez de água. Quantos copos de água bebe o John numa semana? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_037": "O Henry está a fazer bolachas para um concurso de pastelaria local. Quer fazer o dobro do que fez no ano passado. Quando acaba de cozer, percebe que na verdade cozeu 15 bolachas a mais do que pretendia. Deixa cair 5 das suas bolachas quando as está a pôr a arrefecer, e agora tem um total de 110 bolachas. Quantas bolachas fez o Henry no ano passado? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_038": "Uma bomba de gasolina local está a vender gasolina a $3,00 o galão. Uma aplicação está a oferecer $0,20 de cashback por galão se abastecer nessa bomba. Se alguém comprar 10 galões de gasolina, quanto vai custar a gasolina, depois do cashback? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_039": "O Marcell e a Beatrice estão num concurso para ver quem consegue comer mais fruit roll-ups, por isso desenrolam quantos conseguirem encontrar. Infelizmente, alguém comete um erro e o da Beatrice tinha dois roll-ups de largura e 24 roll-ups de comprimento, enquanto o do Marcell tinha 3 roll-ups de largura e 14 roll-ups de comprimento. Se ambos comeram a sua quantidade toda, quantos comeram em média? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
"gsm_040": "O barco da Julia começou a fazer água enquanto ela estava no lago. O barco estava a encher dois litros de água por cada dez pés que ela remava de volta para a margem. Demorou dezasseis segundos a remar vinte pés. A margem estava a sessenta e quatro segundos de distância. Quanta água tinha o barco feito quando a Julia chegou à margem? Usa a calculadora para todos os cálculos; responde com ANSWER: <número>.",
}

def main():
    path = Path("prism/suite/w2_staging/gsm8k_extracted.json")
    suite = json.loads(path.read_text())
    missing = [t["id"] for t in suite["tasks"] if t["id"] not in TRANSLATIONS]
    assert not missing, f"missing translations for: {missing}"
    for t in suite["tasks"]:
        t["content"]["pt_draft"] = TRANSLATIONS[t["id"]]  # DRAFT field —
        # deliberately NOT overwriting content.pt, which stays null until
        # native post-edit per protocol. pt_available() in run_pilot.py
        # checks content.pt specifically, so drafts alone cannot get run
        # as if they were localized.
    Path("prism/suite/w2_staging/gsm8k_pt_draft.json").write_text(
        json.dumps(suite, ensure_ascii=False, indent=1))
    print(f"draft PT written for {len(TRANSLATIONS)}/{len(suite['tasks'])} "
          f"GSM8K tasks -> gsm8k_pt_draft.json (content.pt still null in "
          f"the real suite file — drafts cannot run by accident)")

if __name__ == "__main__":
    main()
